// Spis tokenów
const TOKEN_TYPES = {
    PLUS: '+',
    MINUS: '-',
    MUL: '*',
    DIV: '/',
    MOD: '%',
    EXP: '^',
    EQUALS: '=',
    NEQUALS: '!=',
    GREATER: '>',
    LESSER: '<',
    NGREATER: '<=',
    NLESSER: '>=',
    ABS: '||',
    SIN: 'sin',
    COS: 'cos',
    EXPONENTIAL: 'exp',
    LN: 'ln',
    PI: 'pi',
    EULER: 'e',
    LPAREN: '(',
    RPAREN: ')',
    INTEGER: 'integer',
    FLOAT: 'float',
    IDENTIFIER: 'identifier',
    DIFF1: 'd/dx',
    EOF: 'eof',
};